// Code generated by mockery v2.11.0. DO NOT EDIT.

package mockStorage

import (
	context "architecture_go/pkg/type/context"
	contact "architecture_go/services/contact/internal/domain/contact"

	mock "github.com/stretchr/testify/mock"

	queryParameter "architecture_go/pkg/type/queryParameter"

	testing "testing"

	uuid "github.com/google/uuid"
)

// ContactReader is an autogenerated mock type for the ContactReader type
type ContactReader struct {
	mock.Mock
}

// CountContact provides a mock function with given fields: ctx
func (_m *ContactReader) CountContact(ctx context.Context) (uint64, error) {
	ret := _m.Called(ctx)

	var r0 uint64
	if rf, ok := ret.Get(0).(func(context.Context) uint64); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(uint64)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListContact provides a mock function with given fields: ctx, parameter
func (_m *ContactReader) ListContact(ctx context.Context, parameter queryParameter.QueryParameter) ([]*contact.Contact, error) {
	ret := _m.Called(ctx, parameter)

	var r0 []*contact.Contact
	if rf, ok := ret.Get(0).(func(context.Context, queryParameter.QueryParameter) []*contact.Contact); ok {
		r0 = rf(ctx, parameter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*contact.Contact)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, queryParameter.QueryParameter) error); ok {
		r1 = rf(ctx, parameter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ReadContactByID provides a mock function with given fields: ctx, ID
func (_m *ContactReader) ReadContactByID(ctx context.Context, ID uuid.UUID) (*contact.Contact, error) {
	ret := _m.Called(ctx, ID)

	var r0 *contact.Contact
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *contact.Contact); ok {
		r0 = rf(ctx, ID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*contact.Contact)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, ID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewContactReader creates a new instance of ContactReader. It also registers a cleanup function to assert the mocks expectations.
func NewContactReader(t testing.TB) *ContactReader {
	mock := &ContactReader{}

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
